pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'lolomc-gui-fabric-example'

includeBuild('../../runtime-java') {
    dependencySubstitution {
        substitute module('dev.lolomc:lolomc-gui') using project(':')
    }
}
