plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base { archivesName = "${project.archives_base_name}-${project.minecraft_version}" }

repositories { mavenCentral() }

minecraft {
    mappings channel: 'official', version: project.minecraft_version

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods { lolomc_gui_example { source sourceSets.main } }
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    implementation "dev.lolomc:lolomc-gui:${project.lolomc_version}"
}

sourceSets.main.resources.srcDir('../../examples/fabric-mod/src/main/resources/assets')

processResources {
    inputs.properties([version: project.version, minecraft_version: project.minecraft_version])
    filesMatching('META-INF/mods.toml') {
        expand(version: project.version, minecraft_version: project.minecraft_version)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = project.java_version.toInteger()
    options.encoding = 'UTF-8'
}

java {
    sourceCompatibility = JavaVersion.toVersion(project.java_version)
    targetCompatibility = JavaVersion.toVersion(project.java_version)
    withSourcesJar()
}

jar {
    from('../../LICENSE') { rename { "${it}_${project.base.archivesName.get()}" } }
}

publishing {
    publications { mavenJava(MavenPublication) { from components.java } }
}
