pluginManagement {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'lolomc-gui-forge-fg7-example'

includeBuild('../../runtime-java') {
    dependencySubstitution {
        substitute module('dev.lolomc:lolomc-gui') using project(':')
    }
}
